### ISSUE TITLE
【HTML】iframeについて

### ISSUE THREAD

**Issue by takachaa** [takachaa/.net-Framework#29]
以下のHTMLでjavascriptで自動調整が可能なiframeを差し込むことができたのでメモ

``` html
<iframe id="myFrame" class="frame" src="EstimateInfo2.aspx?rid=40" frameborder="0" scrolling="no"></iframe>
```

``` css
 .frame {
      overflow:hidden;
      overflow-x:hidden;
      overflow-y:hidden;
      height:100%;
      width:100%;
      position:relative;
      top:0px;
      left:0px;
      right:0px;
      bottom:0px;
    }
```

``` javascript
$('#myFrame').load(function () {
              if (typeof $(this).attr('height') == 'undefined') {
                  $(this).height(this.contentWindow.document.documentElement.scrollHeight);
              }
          });
$('#myFrame').triggerHandler('load');
```
